// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: proto/uvgc_custom.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UVGCCustomHandler_GenerateUvgcCustom_FullMethodName = "/UVGCCustomHandler/GenerateUvgcCustom"
)

// UVGCCustomHandlerClient is the client API for UVGCCustomHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UVGCCustomHandlerClient interface {
	GenerateUvgcCustom(ctx context.Context, in *UvgcCustomRequest, opts ...grpc.CallOption) (*UvgcCustomResponse, error)
}

type uVGCCustomHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewUVGCCustomHandlerClient(cc grpc.ClientConnInterface) UVGCCustomHandlerClient {
	return &uVGCCustomHandlerClient{cc}
}

func (c *uVGCCustomHandlerClient) GenerateUvgcCustom(ctx context.Context, in *UvgcCustomRequest, opts ...grpc.CallOption) (*UvgcCustomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UvgcCustomResponse)
	err := c.cc.Invoke(ctx, UVGCCustomHandler_GenerateUvgcCustom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UVGCCustomHandlerServer is the server API for UVGCCustomHandler service.
// All implementations must embed UnimplementedUVGCCustomHandlerServer
// for forward compatibility.
type UVGCCustomHandlerServer interface {
	GenerateUvgcCustom(context.Context, *UvgcCustomRequest) (*UvgcCustomResponse, error)
	mustEmbedUnimplementedUVGCCustomHandlerServer()
}

// UnimplementedUVGCCustomHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUVGCCustomHandlerServer struct{}

func (UnimplementedUVGCCustomHandlerServer) GenerateUvgcCustom(context.Context, *UvgcCustomRequest) (*UvgcCustomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateUvgcCustom not implemented")
}
func (UnimplementedUVGCCustomHandlerServer) mustEmbedUnimplementedUVGCCustomHandlerServer() {}
func (UnimplementedUVGCCustomHandlerServer) testEmbeddedByValue()                           {}

// UnsafeUVGCCustomHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UVGCCustomHandlerServer will
// result in compilation errors.
type UnsafeUVGCCustomHandlerServer interface {
	mustEmbedUnimplementedUVGCCustomHandlerServer()
}

func RegisterUVGCCustomHandlerServer(s grpc.ServiceRegistrar, srv UVGCCustomHandlerServer) {
	// If the following call pancis, it indicates UnimplementedUVGCCustomHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UVGCCustomHandler_ServiceDesc, srv)
}

func _UVGCCustomHandler_GenerateUvgcCustom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UvgcCustomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UVGCCustomHandlerServer).GenerateUvgcCustom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UVGCCustomHandler_GenerateUvgcCustom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UVGCCustomHandlerServer).GenerateUvgcCustom(ctx, req.(*UvgcCustomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UVGCCustomHandler_ServiceDesc is the grpc.ServiceDesc for UVGCCustomHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UVGCCustomHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UVGCCustomHandler",
	HandlerType: (*UVGCCustomHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateUvgcCustom",
			Handler:    _UVGCCustomHandler_GenerateUvgcCustom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/uvgc_custom.proto",
}
